Model(
	Product("Our Product") has (
    	Section("Widget") has (
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
  			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
		)
		
		Section("Applikation") has (
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
  			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
		)

		Section("RouteInformation") has (
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
    		Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
  			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
			Feature("")
    			Spec(""),
    			Why(""),
    			Example(""),
    			Satus(ELICITED)
    		),
		)
	)
)