Model(
  Section("Later releases") has (
    Benefit(93), 
    Cost(1132), 
    Order(2), 
    Feature("extractDataFromProviders") has (Benefit(0), Cost(256)), 
    Feature("geographicalStartingPoint") has (Benefit(0), Cost(32)), 
    Feature("getPopularLocationStatistics") has (Benefit(15), Cost(128)), 
    Feature("getPopularMeansOfTransportStatistics") has (Benefit(25), Cost(128)), 
    Feature("getRoutesStatistics") has (Benefit(0), Cost(128)), 
    Feature("getTravelStatistics") has (Benefit(25), Cost(128)), 
    Feature("getUserStatistics") has (Benefit(2), Cost(128)), 
    Feature("keepAccountPrivate") has (Benefit(0), Cost(32)), 
    Feature("language") has (Benefit(0), Cost(64)), 
    Feature("maxDistToStop") has (Benefit(0), Cost(32)), 
    Feature("minWaitTime") has (Benefit(0), Cost(32)), 
    Feature("multipleDestinations") has (Benefit(10), Cost(8)), 
    Feature("orderDestinations") has (Benefit(0), Cost(16)), 
    Feature("removeDestination") has (Benefit(2), Cost(8)), 
    Feature("renameDestination") has (Benefit(1), Cost(8)), 
    Feature("specifyMeansOfTravel") has (Benefit(13), Cost(4)), 
    Resource("TeamA") has (
      Feature("extractDataFromProviders") has Cost(256), 
      Feature("geographicalStartingPoint") has Cost(32), 
      Feature("getPopularLocationStatistics") has Cost(128), 
      Feature("getPopularMeansOfTransportStatistics") has Cost(128), 
      Feature("getRoutesStatistics") has Cost(128), 
      Feature("getTravelStatistics") has Cost(128), 
      Feature("getUserStatistics") has Cost(128), 
      Feature("keepAccountPrivate") has Cost(32), 
      Feature("language") has Cost(64), 
      Feature("maxDistToStop") has Cost(32), 
      Feature("minWaitTime") has Cost(32), 
      Feature("multipleDestinations") has Cost(8), 
      Feature("orderDestinations") has Cost(16), 
      Feature("removeDestination") has Cost(8), 
      Feature("renameDestination") has Cost(8), 
      Feature("specifyMeansOfTravel") has Cost(4), 
      Cost(1132))))